POST http://localhost:3000/reports
Content-Type: application/json

{
  "make": "toyota",
  "model": "corrola",
  "year": 1980,
  "mileage": 230000,
  "lng": 0,
  "lat": 0,
  "price": 500
}

### Approve existing report
PATCH http://localhost:3000/reports/5
Content-Type: application/json

{
  "approved": false
}

### Get an estimate fon an existing vehicle
GET http://localhost:3000/reports?make=toyota&model=corolla&lng=0&lat=0&mileage=230000&year=1980